FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y qtbase5-dev qtcreator qt5-qmake build-essential cmake g++ libgl1-mesa-dev x11-apps && \
    apt-get clean
