name: Build Qt Calculator App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python and aqtinstall
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64
      
      - name: List Qt bin folder
        run: dir "C:\Users\runneradmin\Qt\5.15.2\msvc2019_64\bin"

      - name: Build Qt project
        shell: powershell
        run: |
          $qtPath = "C:\Users\runneradmin\Qt\5.15.2\msvc2019_64\bin"
          $env:PATH = "$qtPath;$env:PATH"
          qmake Calculator.pro
          nmake


      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalculatorApp
          path: release\*.exe
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
